name: Backend PR Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "DJANGO_SECRET_KEY=dummysecretkey1234567890" >> $GITHUB_ENV
          echo "DJANGO_DEBUG=True" >> $GITHUB_ENV
          echo "DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1" >> $GITHUB_ENV
          echo "DJANGO_CORS_ALLOWED_ORIGINS=http://127.0.0.1:4200,http://localhost:4200" >> $GITHUB_ENV

      - name: Run backend tests
        run: |
          python manage.py test
